### ISSUE TITLE
When I tried to add it python throwed an error

### ISSUE THREAD

**Issue by simonzhekoff** [mishamyrt/dohome_rgb#1]
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/setup.py", line 332, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/root/.homeassistant/custom_components/dohome_rgb/__init__.py", line 27, in async_setup
    hass.data[DOMAIN] = DoHomeGateway(config[DOMAIN][CONF_GATEWAY])
                                      ~~~~~~^^^^^^^^
KeyError: 'dohome_rgb'
2024-01-13 14:26:33.059 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'dohome_rgb.light': Unable to set up component.

**Comment by mishamyrt** [comment]
The configuration format has changed, forgot to update it in the Readme. I have this configuration:

```yaml
light:
  - platform: dohome_rgb
    sids:
      - 7b5b
      - 7cac
      - 7cb7
  - platform: dohome_rgb
    sids:
      - 4f12
      - 77a1
      - e74a
```

It's two chandeliers with 3 bulbs in each. If you need only one, put it in the `sids` array.
